config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new # needed to instantiate the form_for
  end

  def new
    @restaurant = Restaurant.new # needed to instantiate the form_for
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    # no need for app/views/restaurants/create.html.erb
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render new_restaurant_path
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    # no need for app/views/restaurants/update.html.erb
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new # needed to instantiate the form_for
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    # no need for app/views/reviews/create.html.erb
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, as: :select, collection: Restaurant::CATEGORIES, prompt: "select one" %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/restaurants/edit.html.erb
<div>
  <h1>Edit <%= @restaurant.name %> </h1>
  <%= link_to "Back to restaurant list", restaurants_path, class: "btn btn-secondary" %>
</div>
<br>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>All restaurants</h1>
  <%= link_to "✚ Add a restaurant", new_restaurant_path, class: 'btn btn-primary' %>
</div>
<ul class="list-group">
  <% @restaurants.each do |restaurant| %>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <div>
        <%= restaurant.name %>
        <span class="badge badge-light badge-pill"><%= restaurant.category %></span>
        <span class="badge badge-secondary badge-pill"><%= restaurant.reviews.average(:rating)? '★' * restaurant.reviews.average(:rating) : '-'%> (<%= restaurant.reviews.count  %> reviews)</span>
      </div>
      <span>
        <%= link_to "view", restaurant_path(restaurant), class: "badge badge-primary badge-pill" %>
        <%= link_to "edit",edit_restaurant_path(restaurant), class: "badge badge-light badge-pill" %>
        <%= link_to "delete", restaurant_path(restaurant), method: :delete, class: "badge badge-danger badge-pill", data: { confirm: "Are you sure?" } %>
      </span>
    </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<div>
  <h1>Add a new restaurant</h1>
  <%= link_to "Back to restaurant list", restaurants_path, class: "btn btn-secondary" %>
</div>
<br>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1><%= @restaurant.name %> </h1>
  <%= link_to "◀︎ Back to restaurant list", restaurants_path, class: "btn btn-secondary" %>
</div>
<div class="card mb-3">
  <!-- <img src="..." class="card-img-top" alt="..."> -->
  <div class="card-body">
    <span class="badge badge-secondary badge-pill"><%= @restaurant.reviews.average(:rating)? '★' * @restaurant.reviews.average(:rating) : '-'%></span>
    <h5 class="card-title"> <%= @restaurant.category %> restaurant </h5>
    <p class="card-text"> ✉️ - <%= @restaurant.address %> </p>
    <p class="card-text"> ☎️ - <%= @restaurant.phone_number %> </p>
  </div>
</div>
<%= link_to "Edit", edit_restaurant_path(@restaurant), class: "btn btn-warning" %>
<%= link_to "Delete", restaurant_path(@restaurant), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
<%= link_to "Add review", new_restaurant_review_path(@restaurant), class: "btn btn-light" %>
<br>
<br>
<h3>Reviews (<%= @restaurant.reviews.count %>)</h3>
<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <%= review.content %>
      <span class="badge badge-success badge-pill"> <%= "★" * review.rating  %></span>
    </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<div>
  <h1>Add a new review to <%= @restaurant.name %></h1>
  <%= link_to "Back to restaurant page", restaurant_path(@restaurant), class: "btn btn-secondary" %>
</div>
<br>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, as: :radio_buttons, collection: (1..5)%>
  <%= f.submit class: "btn btn-primary"%>
<% end %>